### ISSUE TITLE
broken with grav 1.6?

### ISSUE THREAD

**Issue by huggenknubbel** [Nebulius/grav-plugin-static-social-embeds#1]
Hello, 
it is broken with the Grav version 1.6? 
i can't access the plugin in the Admin Panel.

**Comment by AmauryCarrade** [comment]
Hi, thank you for opening this ticket.

I downloaded a fresh Grav basic installation version 1.6.6 + admin plugin version 1.9.2. Then I installed `static-social-embeds` using the CLI command:

```bash
$ bin/gpm install static-social-embeds
```

And the plugin is correctly detected in the administration dashboard. Same for a production website I own using this plugin and upgrated to 1.6.6 from 1.5.whatever, the plugin is correctly accessible.

![Installed plugins](https://user-images.githubusercontent.com/1417570/56471788-c9603000-6456-11e9-84f5-e4dd08caa964.png)

How is the plugin installed on your side?

**Comment by huggenknubbel** [comment]
i install it like your description. 
i got the plugin in the overview. but if i click on it, i got this
![image](https://user-images.githubusercontent.com/15655280/56472730-9fad0600-6462-11e9-8614-27c2b2d28f3b.png)

**Comment by AmauryCarrade** [comment]
I just checked and I can reproduce this bug on my local installation but not on my production installation. It looks like the problem may be in the translations files, as by switching the account language to French, it works, but fails just like you in English (and probably any other language).

**Comment by AmauryCarrade** [comment]
I fixed the bug on my development server. I'll use this occasion to quickly fix another detail that annoys me and then release the bugfix for everyone. Thanks again for the notice!

**Comment by huggenknubbel** [comment]
i'll thank you for fixing this so quickly.

**Comment by AmauryCarrade** [comment]
I published the fix (plus some others) in the [1.1.4 release](https://github.com/Nebulius/grav-plugin-static-social-embeds/releases/tag/v1.1.4). Wait for GPM to detect the new version and update the plugin through the admin interface (or GPM CLI). :slightly_smiling_face:
