### ISSUE TITLE
Mastodon Media is still loading from the original source

### ISSUE THREAD

**Issue by huggenknubbel** [Nebulius/grav-plugin-static-social-embeds#2]
i created a testpost with some Mastodon toots and the media are still loading from the original soure. 
![grafik](https://user-images.githubusercontent.com/15655280/56476789-90977980-649d-11e9-8073-3d9e09a2d5f6.png)
You can see my testpost [here:](https://blog.huggenknubbel.de/de/testpost) 
Twitter works fine.
(i modified the plugin so it doesn't need to load some stuff from external like the awesome font.)

**Comment by AmauryCarrade** [comment]
I reproduced the problem and am looking into it right now. :)

**Comment by AmauryCarrade** [comment]
The bug has been fixed. I also realised, thanks to your profile, that I forgot to support custom emojis in Mastodon display names, so I fixed that too :slightly_smiling_face: .

![Internal requests & support for custom emojis in display name](https://user-images.githubusercontent.com/1417570/56507893-1b6e8780-6523-11e9-8eaa-ea45071df9f5.png)

**Comment by AmauryCarrade** [comment]
Same as before: wait for GPM to catch [the release](https://github.com/Nebulius/grav-plugin-static-social-embeds/releases/tag/v1.1.5) and update from your admin panel. You will have to fully clear the cache (in your dashboard, _Clear Cache → All caches_, or `bin/grav cache --all`) to re-download the media correctly.

If you don't want to clear the whole cache directory, delete at least the `cache/static-social-embeds` and `images/static-social-embeds` directories.

Thanks again!
