### ISSUE TITLE
Class 'Grav\Plugin\Shortcodes\Shortcode' not found

### ISSUE THREAD

**Issue by mahagr** [Nebulius/grav-plugin-static-social-embeds#4]
The plugin loads a class needing shortcode before shortcode plugin gets initialized:

https://github.com/Nebulius/grav-plugin-static-social-embeds/blob/master/static-social-embeds.php#L26-L27

**Comment by mahagr** [comment]
Actually it's even worse, in CLI plugins are not initialized by default, which means that the Shortcode class will never be there.

**Comment by funilrys** [comment]
@mahagr Can you review my patch when you have a little bit of time? 

I know it's working (tested on stagging, prod and a fresh install) but a quick review from an expert in Grav might be better.

Thanks (again) for your time!

Cheers!

**Comment by mahagr** [comment]
Added comments
