### ISSUE TITLE
ProblemChecker not found

### ISSUE THREAD

**Issue by SjoerdSmeets** [Nebulius/grav-plugin-static-social-embeds#6]
Grav v1.6.21
Admin v1.9.12
Tried to install the plugin, and landed in a Crikey message. 
Class 'Grav\Plugin\Problems\Base\ProblemChecker' not found

Any ideas why this is happening?

**Comment by ghost** [comment]
Grav v1.6.25
Admin v1.9.14
Attempted to install the plugin, but encountered Crikey! message:
Class 'Grav\Plugin\Problems\Base\ProblemChecker' not found

The project was last updated about a year ago. Is this project deprecated?

Regards.

**Comment by AmauryCarrade** [comment]
Fixed thanks to #5. The displayed error was actually misleading.
